name: DevSecOps Security Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Create report directories
        run: |
          mkdir -p security-reports
          mkdir -p zap-reports
          chmod 777 zap-reports

      - name: SAST scan with Semgrep
        run: |
          docker run --rm \
            -v "$PWD:/src" \
            semgrep/semgrep \
            semgrep scan \
            --config auto \
            --json \
            --output /src/security-reports/semgrep.json \
            /src

      - name: Trivy filesystem scan
        run: |
          docker run --rm \
            -v "$PWD:/work" \
            aquasec/trivy:latest \
            fs \
            --scanners vuln,misconfig,secret \
            --format json \
            --output /work/security-reports/trivy-filesystem.json \
            /work

      - name: Build Docker image
        run: |
          docker build \
            -t my-first-pipeline:${{ github.sha }} \
            .

      - name: Trivy Docker image scan
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "$PWD:/work" \
            aquasec/trivy:latest \
            image \
            --format json \
            --output /work/security-reports/trivy-image.json \
            my-first-pipeline:${{ github.sha }}

      - name: Run website
        run: |
          docker run -d \
            --name security-web \
            -p 8080:80 \
            my-first-pipeline:${{ github.sha }}

      - name: Wait for website
        run: |
          for i in {1..20}; do
            if curl --fail --silent http://127.0.0.1:8080 > /dev/null; then
              echo "Website is ready"
              exit 0
            fi
            sleep 2
          done

          docker logs security-web
          exit 1

      - name: DAST scan with OWASP ZAP
        run: |
          docker run --rm \
            --network host \
            -v "$PWD/zap-reports:/zap/wrk/:rw" \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
            -t http://127.0.0.1:8080 \
            -r zap-report.html \
            -J zap-report.json \
            -I

      - name: Upload security reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: devsecops-security-reports
          path: |
            security-reports/
            zap-reports/
          retention-days: 7

      - name: Stop website
        if: always()
        run: docker rm -f security-web || true
